version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '12:30'
      timezone: America/Los_Angeles
    cooldown:
      default-days: 7
      semver-major-days: 14
    groups:
      development-toolchain:
        dependency-type: development
        patterns:
          - '*'
    labels:
      - dependencies
    open-pull-requests-limit: 5
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '12:45'
      timezone: America/Los_Angeles
    cooldown:
      default-days: 7
    labels:
      - dependencies
    open-pull-requests-limit: 5
