/**
 * Markdown Reporter for agentic-ucp-scanner
 * Generates GFM-compliant audit reports suitable for CI/CD artifacts and documentation.
 */

import { AuditResult, DimensionKey } from '../types.js';

function singleLine(value: unknown): string {
  return String(value)
    .replace(/[\u0000-\u001f\u007f-\u009f]/g, ' ')
    .replace(/[\u202a-\u202e\u2066-\u2069]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function escapeMarkdown(value: unknown): string {
  return singleLine(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\|/g, '&#124;');
}

function escapeInlineCode(value: unknown): string {
  return escapeMarkdown(value).replace(/`/g, '&#96;');
}

export function formatMarkdownReport(result: AuditResult): string {
  const { score, checks, target, responseTimeMs, ucpManifest, jsonLd } = result;

  const lines: string[] = [];

  lines.push(`# AI Agent Commerce Audit Report`);
  lines.push(`> Diagnostic output from **agentic-ucp-scanner** using its documented UCP-oriented readiness model.`);
  lines.push('');

  // Badges & Executive Summary
  const gradeColor =
    score.grade === 'A' ? 'brightgreen' : score.grade === 'B' ? 'blue' : score.grade === 'C' ? 'yellow' : 'red';
  lines.push(
    `![Score](https://img.shields.io/badge/Agent_Readiness-${score.totalScore}%2F100-${gradeColor}) ` +
      `![Grade](https://img.shields.io/badge/Grade-${score.grade}-${gradeColor}) ` +
      `![Machine Trust](https://img.shields.io/badge/Machine_Trust_Index-${score.machineTrustIndex}-informational)`
  );
  lines.push('');

  lines.push(`## Summary`);
  lines.push(`| Property | Value |`);
  lines.push(`| :--- | :--- |`);
  lines.push(`| **Target** | \`${escapeInlineCode(target)}\` |`);
  lines.push(`| **Timestamp** | ${result.auditedAt} |`);
  lines.push(`| **Response Time** | ${responseTimeMs} ms |`);
  if (result.httpStatus !== undefined) {
    lines.push(`| **Final HTTP Status** | ${result.httpStatus} |`);
  }
  lines.push(`| **Total Score** | **${score.totalScore} / 100** (Grade ${score.grade}) |`);
  lines.push(`| **Machine Trust Index** | **${score.machineTrustIndex.toFixed(2)}** / 1.00 |`);
  lines.push(`| **Status** | ${escapeMarkdown(score.summary)} |`);
  lines.push('');

  // Dimension Breakdown Table
  lines.push(`## Dimension Breakdown`);
  lines.push(`| Dimension | Score | Max | % | Passed | Warnings | Failed |`);
  lines.push(`| :--- | :---: | :---: | :---: | :---: | :---: | :---: |`);

  const dimKeys: DimensionKey[] = [
    'discovery',
    'entityGraph',
    'intentAndOffers',
    'machinePayments',
    'aiCrawlerAccess',
  ];

  for (const key of dimKeys) {
    const dim = score.dimensions[key];
    lines.push(
      `| **${dim.name}** | ${dim.score.toFixed(1)} | ${dim.maxScore} | ${dim.percentage}% | ${dim.passedCount} | ${dim.warningCount} | ${dim.failedCount} |`
    );
  }
  lines.push('');

  // Machine Trust Entity Graph
  if (ucpManifest || jsonLd?.organizations.length) {
    lines.push(`## Machine Trust Entity Graph`);
    if (ucpManifest?.merchant) {
      lines.push(`- **Merchant:** ${escapeMarkdown(ucpManifest.merchant.name)} (${escapeMarkdown(ucpManifest.merchant.legalName || 'N/A')})`);
      if (ucpManifest.merchant.parentEntity) {
        lines.push(`  - **Parent entity:** ${escapeMarkdown(ucpManifest.merchant.parentEntity)}`);
      }
    }
    if (jsonLd?.parentOrgChain.length) {
      for (const chain of jsonLd.parentOrgChain) {
        lines.push(`- **Schema.org provenance:** ${escapeMarkdown(chain)}`);
      }
    }
    if (ucpManifest?.paymentCapabilities?.protocols.length) {
      lines.push(`- **Declared payment protocols:** ${escapeMarkdown(ucpManifest.paymentCapabilities.protocols.join(', '))}`);
    }
    lines.push('');
  }

  // Detailed Checks
  lines.push(`## Check Details`);
  lines.push(`| Status | ID | Check Name | Score | Details |`);
  lines.push(`| :---: | :--- | :--- | :---: | :--- |`);

  for (const check of checks) {
    const statusIcon =
      check.status === 'PASS' ? '✅ PASS' : check.status === 'WARN' ? '⚠️ WARN' : check.status === 'FAIL' ? '❌ FAIL' : 'ℹ️ INFO';
    lines.push(`| ${statusIcon} | \`${escapeInlineCode(check.id)}\` | **${escapeMarkdown(check.name)}** | ${check.score}/${check.maxScore} | ${escapeMarkdown(check.message)} |`);
  }
  lines.push('');

  // Remediation Plan
  const actionItems = checks.filter((c) => c.status !== 'PASS' && c.remediation);
  if (actionItems.length > 0) {
    lines.push(`## Recommended Remediation Steps`);
    for (let i = 0; i < actionItems.length; i++) {
      const item = actionItems[i];
      lines.push(`${i + 1}. **${escapeMarkdown(item.name)}** (\`${escapeInlineCode(item.id)}\`):`);
      lines.push(`   > ${escapeMarkdown(item.remediation)}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [agentic-ucp-scanner](https://github.com/nymrel/agentic-ucp-scanner), a Nymrel project.*');

  return lines.join('\n');
}
